### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by IanMSeattle** [meeting-guide/api#1]
I've found it very difficult to get engagement from the Area, and was planning to start an opensource project to try and improve AA's online presence.  Really glad to find this project!

My personal view is that AA is failing at making its message available online and in helping newcomers find meetings and help.  It seems like this project is 'solution focused', so I'd love to help.

I created a MySQL database structure to manage meeting details as well as GSR/DCM/Committee membership.  It was done before there had been a decision to move to WordPress which I'm not that familiar with.

The original idea was to scrape whatever data I could from Washington State AA websites, run it through the Google GeoCode API, and create a location aware version of each meeting that could be tied to service positions (eg DCM, GSR, Area & District Committees).  The personally identifiable data including names, email, phone etc would be private to the 'conventional AA service hierarchy'.  

I hoped that by creating a collaborative data structure and making it easily available, we might encourage better quality and availability of timely data for those who need it.

The structure is meant to scale across Areas as well to consolidate the data and make it available for GSO, Areas, Districts, Intergroup offices, and even newcomers.

A couple of points:

1. Prior to population in the databases, extraction/transformation/loading is done in Python 3.5 in a Jupyter Notebook (since there isn't much standardization of data by website as you probably know, first grabbing the data from a website, then running it through a couple of regular expressions to make it more API friendly, then GeoCoding and storing it.

2. There's logic for managing an update process with approvals as well.  The original idea was that anyone could update time/date/location etc data and that a GSR or DCM would approve changes before they went live.  The DB structure tracks these changes by who made them and when.

3. There are currently no CRUD pages for the DBs.

It's not perfect or production code, but if it would be helpful i'd be more than happy to share it if it's helpful.

Ian M

**Comment by joshreisner** [comment]
That's very cool Ian, that's your Online-Meeting-Schedule repo? I know that Seattle Intergroup is currently evaluating its options, you might bring this to their attention. I'd be interested in seeing it in action at the Intergroup or Area level. 

The collaborative contribution / vetting system is beyond what I'm currently doing with 12-Step-Meeting-List and the Meeting Guide app. 

Also you should consider coming to the NAATW conference in Winston-Salem in November.

**Comment by IanMSeattle** [comment]
https://github.com/IanMSeattle/Online-Meeting-Schedule
